title: bright moves for your bodymind
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: move. meditate. expand. change. heal.
color:
  saturation: 0.7258065
  brandStrength: 0.765233
  lightness: 0.747156
  brandColors:
    - '#281e1d'
    - '#fbffff'
    - '#ff593e'
    - '#4b68e0'
    - '#0cfcf9'
  rhythmicContrast: 0.7258065
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
author:
  name: Helgi
  email: helgi.maki@gmail.com
  url: thegrid.ai/brightmoves
opengraph:
  image: null
  type: null
  appId: null
name: 'bright moves '
typography_spectrum: 0.9455084579531103
layout_spectrum: 0.99478
